import { Geist, Geist_Mono, Manrope } from 'next/font/google';
import './globals.css';
import FooterToggle from '@/components/FooterToggle';
// import HeaderToggle from '.HeaderToggle/components/HeaderToggle';
import HeaderToggle from '@/components/HeaderToggle';

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-manrope',
  display: 'swap',
});

export const metadata = {
  title: 'Global Business Tech',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  // HeaderToggle and FooterToggle will hide components on admin routes
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased`} suppressHydrationWarning>
        <HeaderToggle />
        {children}
        <FooterToggle />
      </body>
    </html>
  );
}
