import { Geist, Geist_Mono, Manrope } from 'next/font/google';
import './globals.css';
import FooterSection from '@/components/FooterSection';
import DiscussWithUsSection from '@/components/HomeComponents/DiscussWithUsSection';
// import HeaderToggle from '.HeaderToggle/components/HeaderToggle';
import HeaderToggle from '@/components/HeaderToggle';

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-manrope',
  display: 'swap',
});

export const metadata = {
  title: 'Global Business Tech',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  // HeaderToggle will hide Header on admin routes
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <HeaderToggle />
        {children}
        <DiscussWithUsSection />
        <FooterSection />
      </body>
    </html>
  );
}
